#!/bin/bash
mkdir out
# root -b -q -l FlowExtractor.C
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_etaGap_var1_iter3_.root",1,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_etaGap_var2_iter3_.root",1,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_etaRange_var1_iter3_.root",2,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_etaRange_var2_iter3_.root",2,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_etaRange_var3_iter3_.root",2,3,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_vz_var1_iter3_.root",3,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_vz_var2_iter3_32B7E1D7DCB60D893CDB233D81405A90_.root",3,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_vr_var1_iter3_.root",4,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_vr_var2_iter3_.root",4,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dedx_var1_iter3_.root",5,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dedx_var2_iter3_.root",5,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dca_var1_iter3_.root",6,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dca_var2_iter3_.root",6,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_nHitsFit_var1_iter3_2663.root",7,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_nHitsFit_var2_iter3_.root",7,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_ratio_var1_iter3_.root",8,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_ratio_var2_iter3_.root",8,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_nSigK_var1_iter3_.root",9,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_nSigK_var2_iter3_.root",9,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_mass2_var1_iter3_.root",10,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_mass2_var2_iter3_.root",10,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_pT_var1_iter3_.root",11,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_pT_var2_iter3_.root",11,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dipAngle_var1_iter3_.root",12,1,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dipAngle_var2_iter3_.root",12,2,3)'
root -b -q -l FlowExtractor.C'("./systematic_err/merged_PhiMesonAna_OUTPUT_sys_dipAngle_var3_iter3_.root",12,3,3)'
